/**
 * Type shim for Payload's auto-generated importMap.js.
 * This file is generated by `payload generate:importmap` and is not
 * hand-authored. The `any` type here is the approved exception per
 * constitution/04-technical-law.md §5 (Payload-generated files only).
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export declare const importMap: Record<string, any>
